### ISSUE TITLE
Checkpoints saved after 25 epochs?

### ISSUE THREAD

**Issue by AdarshMJ** [facebookresearch/hgnn#11]
Hi!
1) I wanted to know whether a final checkpoint is saved after performing 25 epochs? If yes, is there a provision to load the existing checkpoint for further training?

2) Is the embedding dimension by default 256? The ZINCEuclideanParams.py says default 256, but while training the embed_size = 4. 

<img width="798" alt="Screenshot 2020-03-19 at 7 05 10 AM" src="https://user-images.githubusercontent.com/24205200/77022572-fc38de00-69af-11ea-9a34-e79d599f196b.png">
<img width="1054" alt="Screenshot 2020-03-19 at 7 04 11 AM" src="https://user-images.githubusercontent.com/24205200/77022592-09ee6380-69b0-11ea-8bd0-88e993fdd64f.png">

**Comment by leuchine** [comment]
Hi,

1. The checkpoint is not saved at the moment, but you can easily do that by adding torch.save(model, PATH) (https://pytorch.org/tutorials/beginner/saving_loading_models.html) in line 110 of https://github.com/facebookresearch/hgnn/blob/master/task/GraphPredictionTask.py

2. We tested different embedding sizes. The embedding size can be specified using the option --embed_size. An embedding size of 256 can obtain reasonably well performance.

Thanks!

Best Regards,
Qi

**Comment by AdarshMJ** [comment]
Hi thank you for the information!
