### ISSUE TITLE
Prepare dataset for Node Classification Task?

### ISSUE THREAD

**Issue by AdarshMJ** [facebookresearch/hgnn#12]
Hi!
Im trying to run the node classification task for my own dataset. I have a CSV file how should I convert it into the format that is currently being used for training?

**Comment by leuchine** [comment]
Hi,

Correct. You just need to follow the format from https://github.com/tkipf/gcn and https://github.com/kimiyoung/planetoid. Thanks!

**Comment by AdarshMJ** [comment]
Thank you.
