### ISSUE TITLE
Tu-Dortmund Datasets are Classfication Tasks?

### ISSUE THREAD

**Issue by AdarshMJ** [facebookresearch/hgnn#14]
Hi!
So im trying to run the experiments for Tu-Dortmund datasets - Proteins and Enzymes. The final best_test that gets printed is the accuracy? Are these experiments available in your paper? I couldnt find the supplementary page in your paper.

Thanks in advance!

**Comment by leuchine** [comment]
Hi,

Yes. The results are accuracy. The results can be found at the appendix E section (https://papers.nips.cc/paper/9033-hyperbolic-graph-neural-networks-supplemental.zip). Thanks!

**Comment by AdarshMJ** [comment]
Thank you!
