### ISSUE TITLE
Hyperparameter Settings for Node Classification Tasks

### ISSUE THREAD

**Issue by martinwhl** [facebookresearch/hgnn#15]
Hi there,
Thanks for the great work. Could you please share the hyperparameter settings for node classification tasks? I tried some settings for the Cora dataset, but the result doesn't end up so well.
Again, thanks a million!

**Comment by leuchine** [comment]
Hi,

Thanks for your interest. Could you please share your parameters used? Also, could you please try to enlarge the number of centroids or embedding sizes based on the default parameters (https://github.com/facebookresearch/hgnn/blob/master/params/NodeClassificationHyperbolicParams.py)? We found the results are very sensitive to these two parameters when running node classification (we did not observe similar phenomenon for graph classification). Thanks!

Best Regards,
Qi

**Comment by martinwhl** [comment]
> 
> 
> Hi,
> 
> Thanks for your interest. Could you please share your parameters used? Also, could you please try to enlarge the number of centroids or embedding sizes based on the default parameters (https://github.com/facebookresearch/hgnn/blob/master/params/NodeClassificationHyperbolicParams.py)? We found the results are very sensitive to these two parameters when running node classification (we did not observe similar phenomenon for graph classification). Thanks!
> 
> Best Regards,
> Qi

I wrongly set the number of centroids and embedding sizes to a relatively small number. I thought the default embedding size may be too big... turns out that I'm wrong.

Thanks for your reply.
