### ISSUE TITLE
External Dataset documentation

### ISSUE THREAD

**Issue by charlesthiebaut** [facebookresearch/hgnn#3]
Hello, 
thank you for your paper and the code. I just had the question regarding the latter, I’m trying to adapt it to run with my own data and was wondering if they are any plans to provide documentation on how to do so ? 

Best, 
Charles.

**Comment by leuchine** [comment]
Hi Charles:

Thanks for your interest in the paper. We did not provide documentation for your purpose at the moment. However, there are two ways to achieve that. If your task is a graph classification task similar to QM9/ZINC, you can just replace the dataset with your own dataset. If your task does not fall into any of the tasks considered, you can just implement your own dataset (refer to the folder dataset) and task (refer to the folder task) classes. Please let me know if you encounter any problem. Thanks!

Best Regards,
Qi

**Comment by charlesthiebaut** [comment]
Thanks for such rapid answer !

My task would in fact be similar to tu_proteins, a graph classification task. I've looked into your code on how the data was prepared but I'm having trouble understanding how graph node are related to node_features. 
In both tu/proteins and QM8 the graph nodes mostly start at 0 and end at (n-1) and are all present (the number of node is n), the node_features is therefore also a list of length n. 

However in other datasets the graph nodes could miss some indices, therefore how would the array of node_features take into account those missing indices ?

**Comment by leuchine** [comment]
Hi Charles:

I am not sure whether I understand your question correctly or not. Please correct me if I am wrong here.

The graph node is basically a dummy node that connects to all other real nodes in the graph (refer to Neural Message Passing for Quantum Chemistry). We used different node features for QM8 and TU Dortmund datasets. As QM8 graphs have labeled nodes, the one hot representations of atom types (e.g. O, N) are used as the node features. As for the unlabeled TU Dortmund graphs, we use degrees of each node as the node features (refer to line 53 - 57 in the file hgnn/data/tu/data_preprocess.py ). So, the node features are unrelated to the number of nodes. Thanks!

Best Regards,
Qi

**Comment by charlesthiebaut** [comment]
Hello, 

Sorry for such unclear question, you answered it though so thank you very much ! 

Best regards,
Charles

**Comment by AdarshMJ** [comment]
In the zinc data folder there are two files  - test_idx and valid_idx, could you please tell me how these two files are generated? Also if I replace it with my own dataset do these files remain?

**Comment by leuchine** [comment]
@AdarshMJ  These are the indices for dev and test data. It is randomly split. If it is your own data, you can just randomly split the dataset if it has not been split yet. Thanks！
