### ISSUE TITLE
Getting `AttributeError: 'NameSpace' has no attribute 'manifold'` error

### ISSUE THREAD

**Issue by seanswyi** [facebookresearch/hgnn#6]
Hello. I'm currently trying to run your code but keep getting the error in the title. More specifically, I downloaded the ZINC data as specified in the README file and ran the program with

```Python
python -m torch.distributed.launch --nproc_per_node=1 ./main.py --task zinc --world_size=1 --embed_manifold hyperbolic
```

and am getting the following traceback:

```Python
Traceback (most recent call last):
  File "./main.py", line 134, in <module>
    gnn_task.run_gnn()
  File "/home/user1/hgnn/task/GraphPredictionTask.py", line 67, in run_gnn
    task_model = GraphPrediction(self.args, self.logger, self.rgnn, self.manifold).cuda()
  File "/home/user1/hgnn/task/GraphPrediction.py", line 34, in __init__
    self.distance = CentroidDistance(args, logger, manifold)
  File "/home/user1/hgnn/hyperbolic_module/CentroidDistance.py", line 31, in __init__
    args.manifold.init_embed(self.centroid_embedding)
AttributeError: 'Namespace' object has no attribute 'manifold'
```

When I run the command without `--embed_manifold hyperbolic` it runs fine. What is the issue that I'm experiencing? I'm having trouble finding the problem and have even deleted and cloned the Git repository again from scratch but am still getting the same error.

**Comment by leuchine** [comment]
Hi:

Thanks for your issue. The `--embed_manifold hyperbolic` changes the embedding representations from the Euclidean space to the hyperbolic space. It seems the args.manifold is not created. Could you please add `args.manifold = manifold` after the line 123 in main.py. This should solve your problem. It seems to be a bug when refactoring the code. Thanks!

Best,
Qi

**Comment by seanswyi** [comment]
Thanks! That indeed fixed the error. :)
