### ISSUE TITLE
Resume training?

### ISSUE THREAD

**Issue by AdarshMJ** [facebookresearch/hgnn#9]
Hi! 

I have been running your code on Colab. Is there a way we can resume the training for a certain task where it was previously left off?

Thanks in advance!

**Comment by leuchine** [comment]
Hi:

Unfortunately, we did not give the checkpoints so far. Some tasks like node classification are fast to train, while others like zinc and qm9 require more time in practice. Thanks!

Best Regards,
Qi

**Comment by AdarshMJ** [comment]
Hi thank you for the information!
